### ISSUE TITLE
Saving Splunk logs with Redshift compression.

### ISSUE THREAD

**Issue by ashishsecdev** [awslabs/amazon-redshift-utils#494]
Is it possible to save Splunk logs in RedShift using compression.

Dummy logs for your reference: [http://docs.splunk.com/images/Tutorial/tutorialdata.zip](url)

**Comment by IanMeyers** [comment]
Provided that the logs are of a fixed structure, then using the correct COPY command settings, you can certainly load and compress those logs using Redshift.

**Comment by ashishsecdev** [comment]
Logs that we are getting aren't of fixed format, does this mean we will not able to use RedShift?. We will use S3 then if not Redshift.

**Comment by IanMeyers** [comment]
Ah I see. Because Redshift is a data warehouse, it generally wants to be able to apply a single schema to a 'table'. That said, Spectrum external tables can support more variable structure including embedded structures and arrays. However, if each row could be of arbitrary format, I would propose that you consider using Athena with a regex serde to get ultimate flexibility.

**Comment by ashishsecdev** [comment]
I already checked that from my end Athena is not possible, so we gonna use the S3 Data Lake option to push our logs.

Thanks for you help Ian.

Cheers!
