### ISSUE TITLE
AnalyzeVacuumUtility - Unhandled arg for project to run

### ISSUE THREAD

**Issue by MatchaBlast** [awslabs/amazon-redshift-utils#500]
Hi Ian,

I'm trying to troubleshoot the below error when ran the following commands. Can you help me understand what the error is? 

```
docker build -t analyze-vacuum .
sudo docker run --net host --rm -it \
-e DB=abc \
-e DB_USER=abc \
-e DB_PWD=xyz \
-e DB_HOST=abc-xyz.xyz.us-east-1.redshift.amazonaws.com \
-e DB_PORT=8192 \
-e MAX_TABLE_SIZE_MB=240 \
-e REQUIRE_SSL=TRUE\
amazon-redshift-utils analyze-vacuum
```
I replaced "amazon-redshift-utils ." to "analyze-vacuum ." for the line docker build as there was error when I ran it

Error:

```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /local/home/vutv/Desktop/amazon-redshift-utils/src/Dockerfile: no such file or directory
Unhandled arg for project to run. Please select from either 'analyze-vacuum', 'column-encoding' or 'unload-copy'
```

Thank you,

**Comment by timjell** [comment]
@MatchaBlast: The error is because you are executing the docker build command in the wrong directory.

You are executing from the 'amazon-redshift-utils/src/' folder. You need to go back up one directory to the 'amazon-redshift-utils/' folder. There you will see the Dockerfile which defines the build of the docker image. There are no docker files in the src folder.
