### ISSUE TITLE
Allow specification of minimum column width in ColumnEncodingUtility

### ISSUE THREAD

**Issue by Limess** [awslabs/amazon-redshift-utils#506]
Currently uses `STRING_REDUCTION_MAX_LENGTH_THRESHOLD` to specify that columns which are under a length of 255 should not be adjusted.

This does not prevent columns being reduced to _under_ that threshold ever, which seems like suprising behaviour.

I'd suggest enforcing that if the new column size is < 255 then it is set to `STRING_REDUCTION_MAX_LENGTH_THRESHOLD` 

i.e. adding a check against this constant here: https://github.com/awslabs/amazon-redshift-utils/blob/master/src/ColumnEncodingUtility/analyze-schema-compression.py#L510-L511 which sets the column length to `STRING_REDUCTION_MAX_LENGTH_THRESHOLD` if it is under that threshold.

**Comment by joeharris76** [comment]
Thanks for the suggestion. Are you saying you would like the utility to **increase** the length of `VARCHAR()` columns that are shorter than `STRING_REDUCTION_MAX_LENGTH_THRESHOLD`? 

This could have negative effects on query performance since extra memory space would be allocated during execution.

**Comment by Limess** [comment]
No, my suggestion is to not decrease anything below that threshold, e.g. if I have a column which is VARCHAR(1000) it shouldn't be reduced below VARCHAR(256). This doesn't seem to be the case now.

**Comment by leisersohn** [comment]
The purpose of `STRING_REDUCTION_MAX_LENGTH_THRESHOLD` is to allow you to skip VARCHAR width length analysis for columns that are below this setting. 
If I understand your suggestion - After analysis if the  `new_column_len` is below STRING_REDUCTION_MAX_LENGTH_THRESHOLD, it should be set to STRING_REDUCTION_MAX_LENGTH_THRESHOLD+1.

I personally would prefer to set it to the new appropriate size, because it already took the time to analyze the column width. 
Perhaps you want to introduce instead a new variable `NEW_COL_LENGTH_MIN` in order to do what you suggested?

**Comment by Limess** [comment]
That seems reasonable. 

The reasoning here is that I'm expecting to run this on tables where I don't necessarily have the full context of each column - and do not want to set column widths to extremely small values given the circumstance. E.G it might be a column containing enums, for which another team is fairly likely to add new values which have length largest than the existing length, but still within a 'reasonable' threshold, say `NEW_COL_LENGTH_MIN` as you propose above.

**Comment by Limess** [comment]
Looks like this was closed by https://github.com/awslabs/amazon-redshift-utils/pull/522, thanks @leisersohn!
