### ISSUE TITLE
Redshift-data API ---redshift-data describe-statement API keeps returning an "UNKNOWN" state

### ISSUE THREAD

**Issue by hardwaals** [awslabs/amazon-redshift-utils#515]
Hi,

Redshift-data execute statement API keeps returning an "UNKNOWN" state as shown below. Kindly help.

aws redshift-data execute-statement      
--database "dev"      
--cluster-identifier "redshift-cluster-1"      
--db-user "awsuser"      
--sql "select * from test;"      
--region "us-east-2"

{
    "ClusterIdentifier": "redshift-cluster-1",
    "CreatedAt": "2020-10-15T20:45:30.676000-05:00",
    "Database": "dev",
    "DbUser": "awsuser",
    "Id": "e847962a-e893-4952-abec-d49a0c034b0c"
}

MacBook-Pro:~$ aws redshift-data describe-statement --id e847962a-e893-4952-abec-d49a0c034b0c --region "us-east-2"

{
    "ClusterIdentifier": "redshift-cluster-1",
    "CreatedAt": "2020-10-15T20:45:30.676000-05:00",
    "Duration": -1,
    "Id": "e847962a-e893-4952-abec-d49a0c034b0c",
    "QueryString": "select * from test;",
    "RedshiftPid": 0,
    "RedshiftQueryId": 0,
    "ResultRows": -1,
    "ResultSize": -1,
    "Status": "**UNKNOWN**",
    "UpdatedAt": "2020-10-15T20:45:31.128000-05:00"

**Comment by joeharris76** [comment]
This issue needs to be raised with AWS Support so that it can be investigated in your environment. They're equipped to immediately review your specific resources and provide further assistance.

Using the support portal, you can securely share your resource identifiers with the Amazon Redshift support team. 

https://console.aws.amazon.com/support/home#/
