### ISSUE TITLE
Can I provide pagerduty's email in WLM QMR notification utility SNS notification email ?

### ISSUE THREAD

**Issue by harish422** [awslabs/amazon-redshift-utils#628]
In step 9 of below WLM QMR notification utility github link, it asks to "click" the link in the email to subscribe for receiving the notification emails. Is clicking the link mandatory ?

https://github.com/awslabs/amazon-redshift-utils/tree/master/src/QMRNotificationUtility

The reason I am asking this is because I would like to provide our pagerduty email address so that our pagerduty will trigger on-call alerts whenever an email is sent to pagerduty's email address. But in this case there is no way to "click" the link in pagerduty's email to subscribe. If clicking the link is not required, we are good may be. Otherwise any workaround to make this use case work ?

Right now triggering an email to my email or any team member email has no significant value. we have to manually track the notification alerts in email.

@saeedma8 @IanMeyers @timjell

**Comment by saeedma8** [comment]
Hi Harish, Thanks for opening a new issue regarding email subscription. One of the parts of SNS subscription process is to confirm the email address:

"[You **must** confirm the subscription before the email address can start to receive messages.](https://docs.aws.amazon.com/sns/latest/dg/sns-email-notifications.html)" This is how SNS topic making sure to send the email to an intended subscriber. 

The workaround as you mentioned to subscribe with any email you have an access then using rules instead of manual tracking e.g., in outlook to forward that to other emails. 

There is no other option to bypass confirmation in SNS subscription process. 

Please let me know if you have any other questions. 

Thank you.
